apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feature-server-cache
  namespace: mlops-feature-store
  labels:
    app: feature-server
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi