apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-server
  namespace: mlops-feature-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-server
  template:
    metadata:
      labels:
        app: feature-server
        name: feature-server
    spec:
      initContainers:
        - name: feature-store-initializer
          image: python:3.9-slim
          command: ['sh', '-c', 'cp /config/feature_store.yaml /feature_repo/feature_store.yaml']
          volumeMounts:
            - name: feast-info
              mountPath: /config
            - name: feature-store-volume
              mountPath: /feature_repo
      containers:
        - name: feature-server
          image: quay.io/rlundber/feast-server:0.3
          args: [ -c, /mnt/feature_repo, serve, -h, 0.0.0.0 ]
          ports:
            - name: feature-server
              containerPort: 6566
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 1Gi
          volumeMounts:
            - mountPath: /mnt/feature_repo
              name: feature-store-volume
            - mountPath: /.cache
              name: feature-server-cache
      volumes:
        - name: feast-info
          configMap:
            name: feast-registry
        - name: feature-store-volume
          persistentVolumeClaim:
            claimName: feature-repo
        - name: feature-server-cache
          persistentVolumeClaim:
            claimName: feature-server-cache